# https://docs.docker.com/compose/compose-file/05-services/#image
services:
  php:
    container_name: my_app
    # https://docs.docker.com/compose/compose-file/build/
    # voir extra-hosts et secrets
    build:
      dockerfile: ./Dockerfile
      args:
        ARG COMPOSER_VERSION: 2.6.5
        ARG PHP_VERSION: 8.2
        ARG BOX_VERSION: 4.5.1
        ARG BOX_CHECKSUM: c24c400c424a68041d7af146c71943bf1acc0c5abafa45297c503b832b9c6b16
        ARG GIT_EMAIL: "seb@local.fr"
        ARG GIT_USERNAME: "seb"
        ARG ALPINE_VERSION: 3.19
    expose:
      - 8000
    ports:
      - target: 8000
        published: 8000
    configs:
      - source: maconfig
        target: /dockerconfig
        mode: 0444
    volumes:
      - type: bind
        source: ./
        target: /app
    user: "0:1000"
    restart: unless-stopped

# https://docs.docker.com/compose/compose-file/08-configs/

configs:
  maconfig:
    file: ./dockerconfig

# https://docs.docker.com/compose/compose-file/10-fragments/
